### ISSUE TITLE
TypeError: t.value.mul is not a function

### ISSUE THREAD

**Issue by cosmicwize** [bitdegree/mass-token-distribution-tool#1]
I'm experiencing the following error when running the script with _node parse.js sample.csv_
`+ t.value.mul((new BigNumber(10)).pow(config.tokenSymbols)).toString(16).padStart(64, "0");
                          ^
TypeError: t.value.mul is not a function`

Installed modules:

> npm list | egrep -i 'got|csv|ethereum|bignumber|fs'
> ├── bignumber.js@7.2.1
> ├─┬ csv@3.1.0
> │ ├── csv-generate@2.1.0
> │ ├── csv-parse@2.5.0
> │ ├─┬ csv-stringify@3.1.1
> ├─┬ ethereumjs-tx@1.3.7
> │ ├── ethereum-common@0.0.18
> │ └─┬ ethereumjs-util@5.2.0
> ├── fs@0.0.1-security
> └─┬ got@8.3.2

Nodejs v9.11.2

Any suggestions?

**Comment by cosmicwize** [comment]
Found the problem. Use bignumber.js 5.0.0 or change the code (mul -> times and add -> plus)

**Comment by fordnox** [comment]
Install 

`npm install bignumber.js@5.0.0`
